version :"3"
services:
    kafka:
        image: wurstmeister/kafka
        ports: - "9092:9092"
        environment: 
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        
    spark:
        image: bitnami/spark
        ports: - "7077:7077"
        environment: - SPARK_MODE = master
        
    postgres:
        image :postgres
        ports: - "5432 : 5432"
        environment: 
                     POSTGRES_DB: stock_data
                     POSTGRES_USER: your_user
                     POSTGRES_PASSWORD: your_password
                     
